POST http://localhost:3000/cursos/programacion
Content-Type: application/json

{
  "id":1,
  "title": "Learn SQL",
  "language": "SQL",
  "views": 2200,
  "level": "basic"
}

######

PUT http://localhost:3000/cursos/programacion/3
Content-Type: application/json

{
  "id": 3,
  "title": "SQL: First steps",
  "language": "SQL",
  "views": 2200,
  "level": "basic"
}

######

PATCH http://localhost:3000/cursos/programacion/3
Content-Type: application/json

{
  "title": "SQL: step by step",
  "language": "SQL with Mysql"
}

######

DELETE http://localhost:3000/cursos/programacion/1